name: CheatBonker-BukkitAPI
version: ${project.version}
main: CheatBonkerBukkitAPI
load: STARTUP
authors: [ Premiering ]
depend: [ ProtocolLib ]
commands:
  waypointtest:
    description: test waypoint command for cheatbonker bukkit api
  waypointremovetest:
    description: fjdsiujfdiogjdfi
  staffmodulestest:
    description: FDGFD*(GDFGDFG
  disallowedmodulestest:
    description: SDFUIG
  notificationtest:
    description: VNBKJVKDFG